CREATE TABLE if not exists Users (
    UserID varchar(255) NOT NULL PRIMARY KEY,
    FirstName varchar(255) NOT NULL,
    LastName varchar(255) NOT NULL,
    Password varchar(50) NOT NULL
);

CREATE TABLE if not exists Tags (
	TagID varchar(255) NOT NULL PRIMARY KEY,
	UserID varchar(255) NOT NULL,
	Name varchar(255) NOT NULL,
	CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE Tags
ADD FOREIGN KEY (UserID) REFERENCES Users(UserID);

CREATE TABLE if not exists UserTag (
	UserID varchar(255) NOT NULL,
	TagID varchar(255) NOT NULL,
	PRIMARY KEY CLUSTERED (UserID , TagID)
); 

ALTER TABLE UserTag
ADD FOREIGN KEY (UserID) REFERENCES Users(UserID);

ALTER TABLE UserTag
ADD FOREIGN KEY (TagID) REFERENCES Tags(TagID);

CREATE TABLE if not exists Lists (
	ListID varchar(255) NOT NULL PRIMARY KEY,
	UserID varchar(255) NOT NULL,
	Name varchar(255) NOT NULL,
	CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE Lists
ADD FOREIGN KEY (UserID) REFERENCES Users(UserID);


CREATE TABLE if not exists Tasks (
	TaskID varchar(255) NOT NULL PRIMARY KEY,
	ListID varchar(255) NOT NULL,
	Summary varchar(255) NOT NULL,
    Task varchar(500) NOT NULL,
	CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DueDate DATE NOT NULL,
    Priority int NOT NULL,
    Status int NOT NULL
);

ALTER TABLE Tasks
ADD FOREIGN KEY (ListID) REFERENCES Lists(ListID);

CREATE TABLE if not exists Remainders (
	RemainderID varchar(255) NOT NULL PRIMARY KEY,
	TaskID varchar(255) NOT NULL,
	Message varchar(255) NOT NULL,
    SentTime DATETIME NOT NULL,
	CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE Remainders
ADD FOREIGN KEY (TaskID) REFERENCES Tasks(TaskID);