name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
        TAG=$(date +%s | tr -d '\n' | tr -d '\r' | tr ':' '_')
        docker build -t db:$TAG .
        docker tag db:$TAG jinshuangniu/advanced1cloud1computing:db-$TAG
        docker push jinshuangniu/advanced1cloud1computing:db-$TAG
